name: Deploy in production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Download code"
        uses: actions/checkout@v4

      - name: "Copy files"
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: /frontend
  
      - name: "Build"
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: APP_NAME
          script: |
            cd /frontend
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true
            docker rmi $APP_NAME || true
            APP_VERSION=$(git tag -l --contains HEAD | tail -n1)
            docker build -t $APP_NAME .
            docker image tag $APP_NAME $APP_NAME:$APP_VERSION
            docker run --name $APP_NAME:$APP_VERSION -d -p 80:80 $APP_NAME
