name: Deploy in production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Copy files"
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: /frontend

    - uses: appleboy/ssh-action@v1.2.0
    - name: "Build"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /frontend
          docker build -t ${{ secrets.APP_NAME }} .
          docker run -d -p 80:80 ${{ secrets.APP_NAME }}
